repos:
  - repo: https://github.com/ddanier/sub-pre-commit.git
    rev: v4.5.1  # MUST match your pre-commit version
    hooks:
      - id: sub-pre-commit
        alias: sysmon_agent
        name: "pre-commit for apps/sysmon_agent/"
        args: ["-p", "apps/sysmon_agent"]
        files: "^apps/sysmon_agent/.*"
        stages: ["pre-commit"]
      - id: sub-pre-commit
        alias: log_analyzer_ml
        name: "pre-commit for apps/log_analyzer_ml/"
        args: [ "-p", "apps/log_analyzer_ml" ]
        files: "^apps/log_analyzer_ml/.*"
        stages: [ "pre-commit" ]
      - id: sub-pre-commit
        alias: backend
        name: "pre-commit for apps/backend/"
        args: ["-p", "apps/backend"]
        files: "^apps/backend/.*"
        stages: ["pre-commit"]